version: "3.5"
services:
  review-php-apache:
    build:
      context: ./php-apache
      dockerfile: Dockerfile
    ports:
      - 8889:80
    volumes:
      - type: bind
        source: "./php-apache/000-default.conf"
        target: "/etc/apache2/sites-enabled/000-default.conf"
      - type: bind
        source: "./php-apache/app"
        target: "/var/www/docker_review"
    depends_on:
      - review-mysql

  review-mysql:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=e2QNqCUd
      - MYSQL_DATABASE=docker_review
 

